### ISSUE TITLE
Incompatibility with minted

### ISSUE THREAD

**Issue by matze** [aclements/latexrun#13]
[minted](http://www.ctan.org/tex-archive/macros/latex/contrib/minted) is a package to highlight code snippets. It shells out and calls the Python program pygments to write some intermediate file. This file is not picked up correctly by latexrun, hence the following example fails to compile with `latexrun --latex-args="-shell-escape" test.tex`:

```latex
\documentclass{minimal}
\usepackage{minted}

\begin{document}
  \begin{minted}{latex}
    \documentclass{minimal}
  \end{minted}
\end{document}
```

Compiling with `latexrun --latex-args="-shell-escape" -O . test.tex` is successful.

**Comment by aclements** [comment]
As a workaround for this problem, you can use "-O ." to put output in the source directory.  Other than that, this seems to be a fundamental limitation of latex's -output-directory flag.

Given the problems with -output-directory (as well as latex routinely overwriting its own output files), I have considered rewriting latexrun to act as a FUSE file system that could intercept all of latex's file system access.  That would solve this problem, but would also increase the complexity of latexrun and dramatically decrease its portability.

I'm open to suggestions, but for now I'm sadly marking this as wontfix.

**Comment by Nadrieril** [comment]
For future reference, this particular problem can be worked around by using `\usepackage[outputdir=latex.out]{minted}`.
