### ISSUE TITLE
Using biber with latex.out

### ISSUE THREAD

**Issue by MrAkergren** [aclements/latexrun#18]
I use biber as the backend for my references, no matter how I try to send in the argument 
``` --output_directory latex.out ```

latexrun just replies that I need to rerun biber on them, any ideas?

**Comment by aclements** [comment]
Hi Oskar. I've never used biber myself, so I'm not familiar with how
it works. Could you post a minimal example set of files and commands
necessary to run biber? Then I might be able to figure out where the
disconnect with latexrun is.

Note that latexrun has quite a bit of specialized knowledge about
bibtex; in particular about how to know which files bibtex read and
wrote based on its output. It might be that biber simply won't work
without a similar level of complex support from latexrun.

Quoth Oskar Åkergren on Mar 04 at 10:12 am:

**Comment by MrAkergren** [comment]
**Background:**
I'm using latex on MacOS X and I got the recommended install from http://www.tug.org/mactex/ so I think `biber` was included, don't think I had to install it separately. I'm using `biber` because of this formatting of the bibliography is demanded by my university. 
***

The files needed are one .tex and one .bib example as follows:
```
%foo.tex
\documentclass[a4paper]{article}
\usepackage[backend=biber, natbib=true, urldate=iso8601, maxnames=2, minnames=1, maxbibnames=10, minbibnames=6, citestyle=numeric-comp]{biblatex}

\addbibresource{ref.bib}

\begin{document}
    \section{Bar}
        This is some text that cites references number one \cite{ref1}, and 
        this is some that mentions number two \cite{ref2}.
\printbibliography      
\end{document}
```
and ref.bib
```
@online{ref1,
    author      = {Aname Ason},
    title       = {FooBar1},
    year        = {2015},
    urldate     = {2015-02-27},
    url         = {www.google.com},
}

@online{ref2,
    author      = {Bname Bson},
    title       = {FooBar2},
    year        = {2014},
    urldate     = {2015-02-27},
    url         = {www.wikipedia.org},
}
```
The commands i use to compile the PDF are
```bash
pdflatex foo
biber foo
pdflatex foo
```
and the compiled document should look like this: 
https://www.dropbox.com/s/aoncxzkwt7j62dz/foo.pdf?dl=0
