### ISSUE TITLE
Does `latexrun` work with XeLaTeX?

### ISSUE THREAD

**Issue by zoresvit** [aclements/latexrun#23]
I was able to get `rubber` work with XeLaTeX, but `latexrun` does seem to be cleaner and modern, so is it possible to use `latexrun` to compile with XeLaTeX?

Thanks.

**Comment by aclements** [comment]
I believe it does (and if it doesn't, I would like it to). Did you try `latexrun --latex-cmd xelatex ...`?

**Comment by apuignav** [comment]
It works perfectly for me.

**Comment by zoresvit** [comment]
True, works great!

By the way, @aclements, any plans to make it Python package so one can install with just `pip install latexrun`?
