### ISSUE TITLE
Python package on PyPi

### ISSUE THREAD

**Issue by zoresvit** [aclements/latexrun#25]
Thank you for your work, I have now switched from `rubber` to `latexrun` :)

It would be also very convenient to be able to install `latexrun` as a [PyPi](https://pypi.python.org/pypi) package.

@aclements, do you have plans to publish it at PyPi? The `setup.py` file could be very simple, like this:

```
import setuptools

setuptools.setup(
    name='latexrun',
    author='Austin Clements',
    author_email='<your.email@gmail.com',
    description='A 21st century LaTeX wrapper',
    keywords='latex',
    license='MIT',
    packages=setuptools.find_packages(),
    scripts=['latexrun'],
    version='0.1',
)
```

If you are not going to, I can do it with my own fork, but I think it's better not to produce extra entities and the best solution is if you could publish it as the developer, through your own PyPi account.

_PS:_ You may also want to explicitly mention that `latexrun` uses Python 3 syntax and will not work under Python 2.7.

Thanks!

**Comment by MonsieurV** [comment]
@zoresvit are you still willing to publish the package on Pypi?

Seems like this library would take great benefit from a fork with a maintainer having time to follow the issues and PRs!

(The work by @aclements was very great. It appears however he has gone to work on other horizons - like its contributions to Go - which let him not much time for hacking Latex)

**Comment by rkiyanchuk** [comment]
@MonsieurV By now I switched to using [tectonic](https://github.com/tectonic-typesetting/tectonic) which has very convenient features: automatically resolves and downloads dependencies, runs TeX and BibTeX as much as needed to build a document, gets rid of mess with temporary files, supports Unicode out of the box, etc. It's fresh and still in beta, but has been working great for me so far. For me tectonic completely superseded `latexrun`, so I've lost the interest to package it :)

Anyone still interested is more then welcome to do it though, using the skeleton of `setup.py` above as a base.
