### ISSUE TITLE
db.temp not found when assigning labels

### ISSUE THREAD

**Issue by FranzSkuffka** [aclements/latexrun#31]
latexrun throws this error if i run it once after assigning a label / an autoref
`error committing control database latex.out/.latexrun.db.tmp: [Errno 2] No such file or directory: 'latex.out/.latexrun.db.tmp' -> 'latex.out/.latexrun.db'`

Everything works fine in the second run though.

**Comment by aclements** [comment]
I don't understand what you mean by "assigning a label / an autoref". Could you give the steps to reproduce this problem?

**Comment by FranzSkuffka** [comment]
I am using the autoref package. But it seems that latexrun is not optimized to work perfectly with all kinds of packages. I am fairly new to latex but the whole ecosystem seems really legacy-ridden and hard to cope with when creating new technologies for latex. So this might be low-priority.

**Comment by FranzSkuffka** [comment]
sorry, I had two latexrun processes run at the same time :expressionless:
