### ISSUE TITLE
Add `.latexrun.db.lock` file

### ISSUE THREAD

**Issue by FranzSkuffka** [aclements/latexrun#33]
The issue with latexrun not finding the `.latexrun.db` file is because it is possible to run latexrun twice at the same time on the same file. I use latexrun in conjunction with a build system to watch changes and I have been running into issues. Not urgent imho but something to consider.

**Comment by aclements** [comment]
Sounds like a good idea. This should be fairly easy to integrate right in to the DB class.

**Comment by FranzSkuffka** [comment]
Btw I find [watch-cli](https://www.npmjs.com/package/watch-cli) super useful for this. Currently tuning visuals for my project thesis about [flextractor](https://github.com/FranzSkuffka/flextractor.git) and the complete automation of watch-cli and latexrun is just great. :yellow_heart:

**Comment by aclements** [comment]
Glad you like it. :)
